# Site settings
title: "Fitz resume"
description: "Server development, Server architecture, A little ML"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Fitz (Joongsoo.Park)"
resume_title:                   "Server development, architecture"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "wndtn853@gmail.com"


resume_header_intro: "<p>I'm java server engineer started 2017. I like 'why' based design and development. Because i think very important word to developer is 'why'.I think developer is must be always possible for answer to their code purpose and design purpose. Developer must make a reasonable choice based on 'why' in many trade-offs.</p>
<p>I'm server enginner. But i have a little skills for ML. I developmented some ML model for news service using tensorflow. And i have patent to ML model. (Block abuse to article comment)</p>
<p>Detail & Contact : <a href='https://www.linkedin.com/in/fitz-sw' target='_blank'>https://www.linkedin.com/in/fitz-sw</a></p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/joongsoo"
  resume_linkedin_url:          "https://www.linkedin.com/in/fitz-sw"
  resume_website_url:           "http://blog.fitz.software"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
